USE DatanautDB;
GO

-- Stäng FK tillfälligt
ALTER TABLE ProjectMember NOCHECK CONSTRAINT ALL;
ALTER TABLE ProjectResource NOCHECK CONSTRAINT ALL;
ALTER TABLE TimeLog NOCHECK CONSTRAINT ALL;
ALTER TABLE Activity NOCHECK CONSTRAINT ALL;
ALTER TABLE MemberSkill NOCHECK CONSTRAINT ALL;

-- Rensa child-tabeller
DELETE FROM TimeLog;
DELETE FROM Activity;
DELETE FROM ProjectResource;
DELETE FROM ProjectMember;
DELETE FROM MemberSkill;

-- Rensa master-tabeller
DELETE FROM Skill;
DELETE FROM Resource;
DELETE FROM Member;
DELETE FROM Project;

-- Rensa lookup-tabeller
DELETE FROM ProjectStatus;
DELETE FROM Role;

-- Starta FK igen
ALTER TABLE ProjectMember CHECK CONSTRAINT ALL;
ALTER TABLE ProjectResource CHECK CONSTRAINT ALL;
ALTER TABLE TimeLog CHECK CONSTRAINT ALL;
ALTER TABLE Activity CHECK CONSTRAINT ALL;
ALTER TABLE MemberSkill CHECK CONSTRAINT ALL;